platform :ios, '8.0'
use_frameworks!
target ‘work’ do
pod 'BmobSDK'
# pod 'RTRootNavigationController'
pod 'HKNewsBannerView', '~> 1.0.1'
pod 'AXWebViewController', '~> 0.1.10'
# pod 'Google-Mobile-Ads-SDK'
pod 'MJExtension'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'MJRefresh', '~> 3.1.12'
# pod 'FDFullscreenPopGesture', '~> 1.1'
pod 'Google-Mobile-Ads-SDK'
pod 'JPush'
pod 'Masonry', '~> 1.0.2'
pod 'BaiduMobStat'
pod 'AFNetworking', '~>3.1.0'
pod 'ChameleonFramework', '~> 2.1.0'
pod 'IQKeyboardManager', '~> 4.0.13'
pod 'SVProgressHUD'
pod 'SAMKeychain', '~> 1.5.2' #钥匙串工具
pod 'Meiqia', '~> 3.3.8'
pod 'iRate', '~> 1.12.1'
pod 'ContextMenu.iOS', '~> 1.1.0'
pod 'Harpy', '~> 4.1.6'
pod 'ReactiveCocoa', '2.5'
pod 'PNChart', '~> 0.8.9'
pod 'SDCycleScrollView', '~> 1.66'
pod 'NYSegmentedControl', '~> 1.1.0'
pod 'WMPageController'
pod 'HSSetTableViewController', '~> 1.2.1'
pod 'SVWebViewController', '~> 1.0'
pod 'ChameleonFramework', '~> 2.1.0'



# pod 'AVOSCloud'
# pod 'AVOSCloudIM'
pod 'BeeCloud', '~> 3.6.1' #包含支付宝微信银联三个渠道
pod 'pop', '~> 1.0.9'
pod 'FDStackView' , '~> 1.0'
pod 'DACircularProgress' , '~> 2.3.1'
pod 'MLLabel' , '~> 1.9.2'
pod 'FMDB', '~> 2.6.2'
pod 'FDFullscreenPopGesture', '~> 1.1'
pod 'WZLBadge', '~> 1.2.4'
pod 'UITableView+FDTemplateLayoutCell', '~> 1.5.beta'
# pod 'XLPhotoBrowser'
pod 'DOPDropDownMenu-Enhanced', '~> 1.0.0'
pod 'BHBPopView'
pod 'TZImagePickerController'
end
